import type { Vehicle } from './types';

export const vehicles: Vehicle[] = [
  {
    id: '1',
    make: 'Toyota',
    model: 'Camry',
    year: 2022,
    price: 25000,
    mileage: 15000,
    engine: '2.5L 4-Cylindres',
    transmission: 'Automatique',
    fuelType: 'Essence',
    description: 'Une berline fiable et économe en carburant, parfaite pour les familles et les trajets quotidiens. Ce modèle est équipé des dernières fonctionnalités de sécurité et d\'un intérieur confortable et spacieux.',
    features: ['Bluetooth', 'Caméra de recul', 'Aide au maintien de voie', 'Régulateur de vitesse adaptatif'],
    images: ['sedan-1', 'sedan-1-gallery-1', 'sedan-1-gallery-2'],
  },
  {
    id: '2',
    make: 'Ford',
    model: 'Explorer',
    year: 2021,
    price: 35000,
    mileage: 22000,
    engine: '3.0L V6',
    transmission: 'Automatique',
    fuelType: 'Essence',
    description: 'SUV spacieux et polyvalent avec trois rangées de sièges et une technologie moderne. Idéal pour les voyages en famille et les aventures, offrant une conduite douce et des performances puissantes.',
    features: ['Apple CarPlay', 'Android Auto', 'Ensemble de remorquage', 'Toit ouvrant'],
    images: ['suv-1', 'suv-1-gallery-1'],
  },
  {
    id: '3',
    make: 'Porsche',
    model: '911',
    year: 2023,
    price: 150000,
    mileage: 5000,
    engine: '3.0L Twin-Turbo Flat-6',
    transmission: 'Automatique',
    fuelType: 'Essence',
    description: 'La voiture de sport emblématique avec des performances à couper le souffle et un design intemporel. Vivez le frisson de la conduite avec une maniabilité et une accélération inégalées.',
    features: ['Sièges en cuir', 'Système audio premium', 'Pack Sport Chrono', 'Volant chauffant'],
    images: ['sportscar-1', 'sportscar-1-gallery-1'],
  },
  {
    id: '4',
    make: 'Chevrolet',
    model: 'Silverado',
    year: 2020,
    price: 40000,
    mileage: 50000,
    engine: '5.3L V8',
    transmission: 'Automatique',
    fuelType: 'Essence',
    description: 'Un pick-up robuste et fiable, prêt pour le travail ou les loisirs. Avec une capacité de remorquage impressionnante et une benne durable, il accomplit les tâches les plus difficiles avec aisance.',
    features: ['4x4', 'Doublure de caisse', 'Sièges chauffants', 'Ensemble de remorquage'],
    images: ['truck-1'],
  },
  {
    id: '5',
    make: 'Honda',
    model: 'Accord',
    year: 2023,
    price: 28000,
    mileage: 8000,
    engine: '1.5L Turbo 4-Cylindres',
    transmission: 'Automatique',
    fuelType: 'Essence',
    description: 'Une berline intermédiaire élégante et confortable avec une excellente économie de carburant. Reconnue pour sa fiabilité et sa grande valeur de revente, l\'Accord est un choix judicieux pour tout conducteur.',
    features: ['Honda Sensing', 'Toit ouvrant', 'Démarrage à distance', 'Chargement sans fil'],
    images: ['sedan-2'],
  },
  {
    id: '6',
    make: 'Tesla',
    model: 'Model Y',
    year: 2022,
    price: 45000,
    mileage: 18000,
    engine: 'Double Moteur',
    transmission: 'Automatique',
    fuelType: 'Électrique',
    description: 'Un SUV tout électrique populaire avec une autonomie impressionnante et une technologie de pointe. Profitez d\'une accélération instantanée et d\'un intérieur minimaliste dominé par un grand écran tactile.',
    features: ['Autopilot', 'Toit en verre panoramique', 'Écran tactile de 15 pouces', 'Mode Sentinelle'],
    images: ['suv-2'],
  },
];

export const vehicleMakes = [...new Set(vehicles.map((v) => v.make))];
