import type { Vehicle } from './types';

export const vehicles: Vehicle[] = [
  {
    id: '1',
    make: 'Toyota',
    model: 'Camry',
    year: 2022,
    price: 25000,
    mileage: 15000,
    engine: '2.5L 4-Cylinder',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    description: 'A reliable and fuel-efficient sedan, perfect for families and daily commutes. This model comes with the latest safety features and a comfortable, spacious interior.',
    features: ['Bluetooth', 'Backup Camera', 'Lane Assist', 'Adaptive Cruise Control'],
    images: ['sedan-1', 'sedan-1-gallery-1', 'sedan-1-gallery-2'],
  },
  {
    id: '2',
    make: 'Ford',
    model: 'Explorer',
    year: 2021,
    price: 35000,
    mileage: 22000,
    engine: '3.0L V6',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    description: 'Spacious and versatile SUV with three rows of seating and modern tech. Ideal for family road trips and adventures, offering a smooth ride and powerful performance.',
    features: ['Apple CarPlay', 'Android Auto', 'Towing Package', 'Sunroof'],
    images: ['suv-1', 'suv-1-gallery-1'],
  },
  {
    id: '3',
    make: 'Porsche',
    model: '911',
    year: 2023,
    price: 150000,
    mileage: 5000,
    engine: '3.0L Twin-Turbo Flat-6',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    description: 'The iconic sports car with breathtaking performance and timeless design. Experience the thrill of driving with unparalleled handling and acceleration.',
    features: ['Leather Seats', 'Premium Sound System', 'Sport Chrono Package', 'Heated Steering Wheel'],
    images: ['sportscar-1', 'sportscar-1-gallery-1'],
  },
  {
    id: '4',
    make: 'Chevrolet',
    model: 'Silverado',
    year: 2020,
    price: 40000,
    mileage: 50000,
    engine: '5.3L V8',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    description: 'A rugged and dependable pickup truck ready for work or play. With impressive towing capacity and a durable bed, it handles the toughest jobs with ease.',
    features: ['4x4', 'Bed Liner', 'Heated Seats', 'Trailering Package'],
    images: ['truck-1'],
  },
  {
    id: '5',
    make: 'Honda',
    model: 'Accord',
    year: 2023,
    price: 28000,
    mileage: 8000,
    engine: '1.5L Turbo 4-Cylinder',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    description: 'A stylish and comfortable midsize sedan with excellent fuel economy. Known for its reliability and high resale value, the Accord is a smart choice for any driver.',
    features: ['Honda Sensing', 'Moonroof', 'Remote Start', 'Wireless Charging'],
    images: ['sedan-2'],
  },
  {
    id: '6',
    make: 'Tesla',
    model: 'Model Y',
    year: 2022,
    price: 45000,
    mileage: 18000,
    engine: 'Dual Motor',
    transmission: 'Automatic',
    fuelType: 'Electric',
    description: 'A popular all-electric SUV with impressive range and cutting-edge technology. Enjoy instant acceleration and a minimalist interior dominated by a large touchscreen.',
    features: ['Autopilot', 'Panoramic Glass Roof', '15-inch Touchscreen', 'Sentry Mode'],
    images: ['suv-2'],
  },
];

export const vehicleMakes = [...new Set(vehicles.map((v) => v.make))];
