-- Create the vehicles table
CREATE TABLE public.vehicles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  make text,
  model text,
  year integer,
  price real,
  mileage integer,
  engine text,
  transmission text,
  fuel_type text,
  description text,
  features text[],
  image_urls text[]
);

-- Set up Row Level Security
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Public vehicles are viewable by everyone."
  ON public.vehicles FOR SELECT
  USING ( true );

-- Create policy for authenticated users to insert
CREATE POLICY "Users can insert their own vehicles."
  ON public.vehicles FOR INSERT
  WITH CHECK ( true );

-- Create a bucket for vehicle images
INSERT INTO storage.buckets (id, name, public)
VALUES ('vehicle-images', 'vehicle-images', true)
ON CONFLICT (id) DO NOTHING;

-- Create policy for public read access on images
CREATE POLICY "Vehicle images are publicly accessible."
  ON storage.objects FOR SELECT
  USING ( bucket_id = 'vehicle-images' );

-- Create policy for authenticated users to upload images
CREATE POLICY "Anyone can upload vehicle images."
  ON storage.objects FOR INSERT
  WITH CHECK ( bucket_id = 'vehicle-images' );
